[[constraint]]
  name = "github.com/retailnext/hllpp"
  revision = "01496c854800396a767f4f034a2bb58af2924b25"
  source = "https://github.com/LiveRamp/hllpp"

# Use an old, pinned version of the cockroach DB keyspace encoding utilities.
[[constraint]]
  name = "github.com/cockroachdb/cockroach"
  source = "https://github.com/jgraettinger/cockroach-encoding.git"

# Required by Etcd, which is currently not compatible with v1.1.2
[[override]]
  name = "github.com/ugorji/go"
  version = "=v1.1.1"

# We require that gorocksdb match our RocksDB version pin (currently 5.17.2)
[[constraint]]
  name = "github.com/tecbot/gorocksdb"
  version = "=v1.2.0"
  source = "https://github.com/LiveRamp/gorocksdb.git"

# TODO: remove this constraint once the import paths are fixed to omit v2/pkg
# PS-1135
[[constraint]]
  name = "github.com/LiveRamp/gazette"
  revision = "49c4ae6934cabaf52f21b5fc57bb7d6379c06ec5"
  source = "https://github.com/gazette/core"
