
[[constraint]]
  name = "github.com/cockroachdb/cockroach"
  source = "https://github.com/jgraettinger/cockroach-encoding.git"

[[constraint]]
  name = "github.com/LiveRamp/gazette"
  source = "https://github.com/LiveRamp/gazette.git"
  branch = "master"

# bbolt is a transitive dependency from coreos/etcd. At this time, the current
# version of etcd (v3.3.9) has a dependency on this version of bbolt which is
# not part of etcd's Gopkg.toml.
[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"

# We require that gorocksdb match our RocksDB version pin (currently 5.14.2)
[[constraint]]
  name = "github.com/tecbot/gorocksdb"
  version = "=v1.2.0"
  source = "https://github.com/LiveRamp/gorocksdb.git"

# Required by Etcd, which is currently not compatible with v1.1.2
[[override]]
  name = "github.com/ugorji/go"
  version = "=v1.1.1"

[[constraint]]
  name = "github.com/retailnext/hllpp"
  revision = "01496c854800396a767f4f034a2bb58af2924b25"
  source = "https://github.com/LiveRamp/hllpp"

# Require an unreleased `master` revision of gogo/protobuf, which includes the "goproto_unkeyed_all"
# and "goproto_sizecache_all" extensions.
[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "e14cafb6a2c249986e51c4b65c3206bf18578715"
