# Default values for factable.
# This is a YAML-formatted file.

extractor:
  replicaCount: 1
  image:
    repository: liveramp/factable
    binary: /go/bin/extractor

  extraArgs:
    --factable.instance: "{{.Release.Name}}"
    --factable.schema:   "/factable/schema/{{.Release.Name}}"
    --factable.deltas:   "app.gazette.dev/message-type=DeltaEvent,app.gazette.dev/instance={{.Release.Name}}"

vtable:
  replicaCount: 1
  image:
    repository: liveramp/factable
    binary: /go/bin/vtable

  extraArgs:
    --factable.instance:  "{{.Release.Name}}"
    --factable.schema:    "/factable/schema/{{.Release.Name}}"
    --factable.deltas:    "app.gazette.dev/message-type=DeltaEvent,app.gazette.dev/instance={{.Release.Name}}"
