# Default values for factable.
# This is a YAML-formatted file.

extractor:
  replicaCount: 1
  image:
    repository: liveramp/factable
    binary: /go/bin/extractor

  extraArgsTemplate: |
    --factable.instance={{ .Release.Name }} \
    --factable.schema=/factable/schema \
    --factable.deltas={{ .Values.global.deltasSelector | quote }}

vtable:
  replicaCount: 1
  image:
    repository: liveramp/factable
    binary: /go/bin/vtable

  arenaSize: "16777216"
  maxArenas: 8

  extraArgsTemplate: |
    --factable.instance={{ .Release.Name }} \
    --factable.schema=/factable/schema \
    --factable.deltas={{ .Values.global.deltasSelector | quote }} \
    --factable.arenaSize={{ .Values.arenaSize }} \
    --factable.maxArenas={{ .Values.maxArenas }} \

global:
  deltasSelector: "app.gazette.dev/message-type = DeltaEvent"